export default {
  axios: {
    baseURL: 'https://keiotaiwan.org',
  },
  locale: 'zh_tw',
  slideshow: {
    changeInterval: 3000,
  },
  members: [
    {
      row: 0,
      col: 1,
      role: ['會長', 'SFC校區長'],
      name: '陳貝瓜',
      otherName: 'Lydia',
      campus: 'SFC',
      photoName: 'Lydia',
    },
    {
      row: 1,
      col: 0,
      role: ['三田校區長'],
      name: '中台伊晴',
      otherName: 'Iharu',
      campus: '三田',
      photoName: '中台伊晴',
    },
    {
      row: 1,
      col: 1,
      role: ['副會長'],
      name: '染谷めい',
      campus: 'SFC',
      photoName: '染谷',
    },
    {
      row: 1,
      col: 2,
      role: ['日吉校區長'],
      name: 'Heather',
      campus: '日吉',
      photoName: 'Heather',
    },
    {
      row: 2,
      col: 0,
      role: ['會計&吉祥物'],
      name: 'Issey',
      campus: 'SFC',
      photoName: 'Issey',
    },
    {
      row: 2,
      col: 1,
      role: ['美宣'],
      name: '子誼',
      campus: 'SFC',
      photoName: '',
    },
    {
      row: 2,
      col: 2,
      role: ['資訊部'],
      name: 'Andy',
      campus: 'SFC',
      photoName: 'Andy',
    },
    {
      row: 3,
      col: 0,
      role: ['公關部'],
      name: 'Emily',
      campus: 'SFC',
      photoName: 'Emily',
    },
    {
      row: 3,
      col: 1,
      role: ['公關部'],
      name: 'ゆう',
      campus: 'SFC',
      photoName: 'Yu',
    },
    {
      row: 3,
      col: 2,
      role: ['活動部長'],
      name: 'Sean',
      campus: 'SFC',
      photoName: 'Sean',
    },
    {
      row: 4,
      col: 0,
      role: ['活動部'],
      name: 'Azusa',
      campus: '日吉',
      photoName: 'Azusa',
    },
    {
      row: 4,
      col: 1,
      role: ['活動部'],
      name: '筠婷',
      campus: '日吉',
      photoName: '筠婷',
    },
    {
      row: 4,
      col: 2,
      role: ['活動部'],
      name: 'Lin',
      campus: 'SFC',
      photoName: 'Lin',
    },
    {
      row: 5,
      col: 2,
      role: ['永遠的學弟妹長'],
      name: 'Bill',
      campus: 'SFC?',
      photoName: 'Bill',
    },
  ],
  ktsa: {
    contacts: {
      facebook: {
        url: 'https://www.facebook.com/keiotaiwan/',
      },
      line: {
        url: 'https://linecorp.com/',
      },
      mail: {
        url: 'keiotaiwaneseofficial@gmail.com',
      },
      twitter: {
        url: 'https://twitter.com/keiotaiwan/',
      },
    },
  },
  campuses: [
    {
      name: {
        en: 'Mita',
        ja: '三田',
        zh_tw: '三田',
      },
      address: '',
      url: '',
    },
    {
      name: {
        en: 'Hiyoshi',
        ja: '日吉',
        zh_tw: '日吉',
      },
      address: '',
      url: '',
    },
    {
      name: {
        en: 'SFC',
        ja: '湘南藤沢',
        zh_tw: '湘南藤澤',
      },
      address: '',
      url: 'https://www.sfc.keio.ac.jp/',
    },
  ],
};
